[package]
name = "chesspiece-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
packer = { path = "../crates/packer" }

[build-dependencies]
tauri-build = { version = "2" }
